id: I1824410B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T00:35:27+00:00'
last_modified: '2022-06-09T06:45:36.238641+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1GS58442
  title: གཏེར་འབྱུང་ཆེན་མོ་དང་དྲི་བ་རྣམ་པར་རྒྱལ་བའི་ཁང་བཟང་སོགས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    A294:
      image_group_id: I1GS58444
      title: Volume 1 of gter 'byung chen mo dang dri ba rnam par rgyal ba'i khang
        bzang sogs
      total_pages: 316
      order: 1
      base_file: A294.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
