id: P007864
initial_creation_type: ocr
source_metadata:
  id: bdr:W1GS58442
  title: གཏེར་འབྱུང་ཆེན་མོ་དང་དྲི་བ་རྣམ་པར་རྒྱལ་བའི་ཁང་བཟང་སོགས
  author: ''
  volumes:
    ca983746913d4ed9ae15e1f3b546c9d9:
      image_group_id: I1GS58444
      title: ''
      volume_number: 1
      total_pages: 316
ebook_metadata:
  title: གཏེར་འབྱུང་ཆེན་མོ་དང་དྲི་བ་རྣམ་པར་རྒྱལ་བའི་ཁང་བཟང་སོགས
  author: ''
  sku: P007864
  cover: cover.jpg
  layers:
  - pagination
